name = "Priam"
license = "MIT"
licenselink = "https://github.com/fabston/hugo-theme-priam/blob/master/LICENSE.md"
description = "Minimal theme for Hugo"
homepage = "https://priam.fabston.dev"
tags = ["minimal", "blog", "personal", "clean", "simple", "minimalist"]
features = ["blog"]
min_version = "0.49"

[author]
  name = "Fabston"
  homepage = "https://fabston.dev"
