baseurl: "https://priam.fabston.dev"
languageCode: "en-us"
title: "Priam Hugo Theme"
theme: "priam"
paginate: 8
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

pygmentsUseClasses: true
pygmentsCodeFences: true

permalinks:
  post: "/post/:slug/"

author:
  name: Priam Theme
  
menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Posts
      url: "post/"
      weight: 3

params:
  description: "A minimal Hugo website"
  footer: ""
  plausible: ""
  goatcounter: ""

markup:
  goldmark:
    renderer:
      unsafe: true